CC-4408: update java to version 11 for internal services
zenoss/centos-base pull request #22
Opened 2021-02-25 08:12 UTC by Deer-WarLord

2021-02-25 13:56 UTC, jpeacock-zenoss requested changes

2021-02-25 13:56 UTC, jpeacock-zenoss commented on Dockerfile.java.in
> +RUN yum -y --setopt=tsflags="nodocs" install java-1.8.0-openjdk-headless && /sbin/scrub.sh
Is there any reason why Java 8 cannot be installed on only the images that require it?

I don't really want to distribute both Java 11 _and_ Java 8 to all images.

2021-03-01 12:30 UTC, Deer-WarLord commented on Dockerfile.java.in
> +RUN yum -y --setopt=tsflags="nodocs" install java-1.8.0-openjdk-headless && /sbin/scrub.sh
Of course, we can do that in each image for the services that require java 11 or java 8. 
But I'd view that as a compromise for a java transition period from 8 to 11.

2021-03-01 13:10 UTC, jpeacock-zenoss commented on Dockerfile.java.in
> +RUN yum -y --setopt=tsflags="nodocs" install java-1.8.0-openjdk-headless && /sbin/scrub.sh
If the serviced-isvcs image started with the non-java centos-base image and installed Java 8, there would be no need to juggle different versions of Java in the configuration.

2021-03-01 14:34 UTC, Deer-WarLord commented on Dockerfile.java.in
> +RUN yum -y --setopt=tsflags="nodocs" install java-1.8.0-openjdk-headless && /sbin/scrub.sh
Yes but we need both version of java for serviced-isvcs image for different containers

2021-03-02 14:23 UTC, closed without merging